spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3312/smddd?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 4321